Repository Team-Catxi/Catxi_BackEnd, pull requests merged in 2025-05, with the labels that each got.

#10 [FEAT] DB 환경 분리
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ⚙ Setting

#13 [FEAT] 채팅 메시지 저장 로직 추가
  src/main/java/com/project/catxi/chat/controller/ChatController.java
  src/main/java/com/project/catxi/chat/domain/ChatMessage.java
  src/main/java/com/project/catxi/chat/dto/ChatMessageRes.java
  src/main/java/com/project/catxi/chat/dto/ChatMessageSendReq.java
  src/main/java/com/project/catxi/chat/repository/ChatMessageRepository.java
  src/main/java/com/project/catxi/chat/repository/ChatRoomRepository.java
  src/main/java/com/project/catxi/chat/service/ChatMessageService.java
  src/main/java/com/project/catxi/common/api/error/ChatRoomErrorCode.java
  src/main/java/com/project/catxi/common/api/error/MemberErrorCode.java
  src/main/java/com/project/catxi/member/repository/MemberRepository.java
Labels: ✨ Feature

#20 [FEAT] 채팅방 참여 API 구현
  src/main/java/com/project/catxi/chat/controller/ChatController.java
  src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
  src/main/java/com/project/catxi/chat/service/ChatRoomService.java
  src/main/java/com/project/catxi/common/api/error/ChatRoomErrorCode.java
Labels: ✨ Feature

#22 [FEAT] 채팅방 나가기 API 구현
  src/main/java/com/project/catxi/chat/controller/ChatController.java
  src/main/java/com/project/catxi/chat/domain/ChatParticipant.java
  src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
  src/main/java/com/project/catxi/chat/service/ChatMessageService.java
  src/main/java/com/project/catxi/chat/service/ChatRoomService.java
  src/main/java/com/project/catxi/common/api/error/ChatParticipantErrorCode.java
Labels: ✨ Feature

#27 [BUG] ChatParticipant isActive 필드명 변경
  src/main/java/com/project/catxi/chat/domain/ChatParticipant.java
  src/main/java/com/project/catxi/chat/service/ChatRoomService.java
Labels: 🐞 BugFix

#19 [FEAT] Dockerfile 설정
  Dockerfile
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ⚙ Setting, 🌏 Deploy

#28 [FEAT] 채팅방 목록 조회 API
  .gitignore
  build.gradle
  src/main/java/com/project/catxi/chat/controller/ChatController.java
  src/main/java/com/project/catxi/chat/dto/ChatRoomRes.java
  src/main/java/com/project/catxi/chat/repository/ChatRoomRepository.java
  src/main/java/com/project/catxi/chat/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/project/catxi/chat/repository/ChatRoomRepositoryCustomImpl.java
  src/main/java/com/project/catxi/chat/service/ChatRoomService.java
  src/main/java/com/project/catxi/common/config/QuerydslConfig.java
Labels: ✨ Feature
