Repository Team-Catxi/Catxi_BackEnd, pull requests merged in 2025-09, with the labels that each got.

#134 [BUGFIX] 로그인 필터 인증 허용
  .gitignore
  src/main/java/com/project/catxi/common/config/security/SecurityConfig.java
  src/main/java/com/project/catxi/common/jwt/JwtFilter.java
Labels: 🐞 BugFix

#136 [FEAT] /admin 권한 제어
  src/main/java/com/project/catxi/common/auth/controller/BlacklistController.java
  src/main/java/com/project/catxi/common/auth/service/OAuthLoginService.java
  src/main/java/com/project/catxi/common/auth/service/TokenService.java
  src/main/java/com/project/catxi/common/config/security/SecurityConfig.java
  src/main/java/com/project/catxi/common/jwt/JwtTokenProvider.java
  src/main/java/com/project/catxi/common/jwt/JwtUtil.java
  src/main/java/com/project/catxi/member/controller/MemberController.java
  src/main/java/com/project/catxi/member/dto/CustomUserDetails.java
  src/main/resources/application.yml
Labels: ✨ Feature

#144 [FEAT] DB 마이그레이션
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/changelog/v1.0/009-fix-report-nullable-constraints.xml
Labels: ✨ Feature

#148 [FIX] 방 삭제시 해당 방인원 실시간 나가지는 기능으로 변경
  src/main/java/com/project/catxi/chat/config/RoomDeletedEventListener.java
  src/main/java/com/project/catxi/chat/dto/RoomDeletedEvent.java
  src/main/java/com/project/catxi/chat/dto/RoomEventMessage.java
  src/main/java/com/project/catxi/chat/service/ChatRoomService.java
  src/main/java/com/project/catxi/chat/service/RedisPubSubService.java
  src/main/java/com/project/catxi/common/config/RedisConfig.java
Labels: ✨ Feature

#146 [FIX] 회원탈퇴 로직 수정
  build.gradle
  src/main/java/com/project/catxi/chat/repository/ChatMessageRepository.java
  src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
  src/main/java/com/project/catxi/chat/repository/ChatRoomRepository.java
  src/main/java/com/project/catxi/chat/repository/KickedParticipantRepository.java
  src/main/java/com/project/catxi/common/api/error/MemberErrorCode.java
  src/main/java/com/project/catxi/common/auth/controller/OAuthController.java
  src/main/java/com/project/catxi/common/auth/infra/KakaoAccessTokenRepository.java
  src/main/java/com/project/catxi/common/auth/kakao/KakaoFeignClient.java
  src/main/java/com/project/catxi/common/auth/kakao/KakaoUnlinkRes.java
  src/main/java/com/project/catxi/common/auth/service/BlacklistService.java
  src/main/java/com/project/catxi/common/auth/service/OAuthLoginService.java
  src/main/java/com/project/catxi/common/auth/service/TokenService.java
  src/main/java/com/project/catxi/common/config/FeignConfig.java
  src/main/java/com/project/catxi/member/controller/MemberController.java
  src/main/java/com/project/catxi/member/domain/DeleteLog.java
  src/main/java/com/project/catxi/member/repository/DeleteLogRepository.java
  src/main/java/com/project/catxi/member/repository/MatchHistoryRepository.java
  src/main/java/com/project/catxi/member/service/MemberService.java
  src/main/java/com/project/catxi/report/repository/ReportRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🔨 Refactor

#155 [FEAT] Ready 요청 결과에 실시간 메시지 전송
  src/main/java/com/project/catxi/chat/repository/ChatParticipantRepository.java
  src/main/java/com/project/catxi/chat/service/RedisPubSubService.java
  src/main/java/com/project/catxi/chat/service/TimerService.java
  src/main/java/com/project/catxi/common/config/RedisConfig.java
Labels: ✨ Feature

#153 [FEAT] Redis기반 이벤트 드리븐 아키텍처 FCM 푸시 알림
  .gitignore
  ansible/deploy-playbook.yml
  ansible/templates/env.j2
  build.gradle
  docker-compose.yml
  src/main/java/com/project/catxi/chat/service/ChatMessageService.java
  src/main/java/com/project/catxi/chat/service/ReadyService.java
  src/main/java/com/project/catxi/common/api/error/FcmErrorCode.java
  src/main/java/com/project/catxi/common/config/FcmConfig.java
  src/main/java/com/project/catxi/common/config/RedisConfig.java
  src/main/java/com/project/catxi/fcm/controller/FcmController.java
  src/main/java/com/project/catxi/fcm/dto/FcmActiveStatusReq.java
  src/main/java/com/project/catxi/fcm/dto/FcmNotificationEvent.java
  src/main/java/com/project/catxi/fcm/dto/FcmTokenUpdateReq.java
  src/main/java/com/project/catxi/fcm/dto/FcmTokenUpdateRes.java
  src/main/java/com/project/catxi/fcm/service/FcmActiveStatusService.java
  src/main/java/com/project/catxi/fcm/service/FcmEventConsumer.java
  src/main/java/com/project/catxi/fcm/service/FcmEventPublisher.java
  src/main/java/com/project/catxi/fcm/service/FcmNotificationService.java
  src/main/java/com/project/catxi/fcm/service/FcmTokenService.java
  src/main/java/com/project/catxi/member/domain/Member.java
  src/main/java/com/project/catxi/member/repository/MemberRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/changelog/db.changelog-master.xml
  src/main/resources/db/changelog/v1.0/010-create-fcm-token-table.xml
Labels: ✨ Feature

#161 [FIX] 무중단 액세스 토큰 재발급
  src/main/java/com/project/catxi/common/api/error/MemberErrorCode.java
  src/main/java/com/project/catxi/common/auth/service/TokenService.java
  src/main/java/com/project/catxi/common/config/security/JwtFilterConfig.java
  src/main/java/com/project/catxi/common/jwt/JwtFilter.java
  src/main/java/com/project/catxi/common/jwt/JwtUtil.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#163 [FIX] FCM 중복 발송 방지 및 활성 상태 관리 개선
  src/main/java/com/project/catxi/chat/config/StompEventListener.java
  src/main/java/com/project/catxi/fcm/service/FcmActiveStatusService.java
  src/main/java/com/project/catxi/fcm/service/FcmEventConsumer.java
Labels: 🐞 BugFix

#165 [FIX] 로드밸런싱 환경에서 FCM 중복 발송 방지
  src/main/java/com/project/catxi/common/service/RedisDistributedLockService.java
  src/main/java/com/project/catxi/fcm/service/FcmEventConsumer.java
  src/main/java/com/project/catxi/fcm/service/FcmEventPublisher.java
  src/main/java/com/project/catxi/fcm/util/FcmBusinessKeyGenerator.java
Labels: 🐞 BugFix

#169 [REFACTOR] Redis pub/sub 방식에서 메시지 큐로 전환
  src/main/java/com/project/catxi/chat/service/ChatMessageService.java
  src/main/java/com/project/catxi/chat/service/ReadyService.java
  src/main/java/com/project/catxi/common/config/RedisConfig.java
  src/main/java/com/project/catxi/common/service/RedisDistributedLockService.java
  src/main/java/com/project/catxi/fcm/service/FcmActiveStatusService.java
  src/main/java/com/project/catxi/fcm/service/FcmEventConsumer.java
  src/main/java/com/project/catxi/fcm/service/FcmEventPublisher.java
  src/main/java/com/project/catxi/fcm/service/FcmQueueConsumer.java
  src/main/java/com/project/catxi/fcm/service/FcmQueueService.java
  src/main/java/com/project/catxi/fcm/util/FcmBusinessKeyGenerator.java
Labels: ✨ Feature

#171 [REFACTOR] 불필요 로직 및 과도한 로깅 제거
  src/main/java/com/project/catxi/chat/config/StompEventListener.java
  src/main/java/com/project/catxi/chat/service/ChatMessageService.java
  src/main/java/com/project/catxi/chat/service/ReadyService.java
  src/main/java/com/project/catxi/fcm/dto/FcmNotificationEvent.java
  src/main/java/com/project/catxi/fcm/service/FcmActiveStatusService.java
  src/main/java/com/project/catxi/fcm/service/FcmNotificationService.java
  src/main/java/com/project/catxi/fcm/service/FcmQueueConsumer.java
  src/main/java/com/project/catxi/fcm/service/FcmQueueService.java
  src/main/java/com/project/catxi/fcm/service/FcmTokenService.java
  src/main/java/com/project/catxi/fcm/util/FcmBusinessKeyGenerator.java
Labels: 🔨 Refactor
